import { MD3Colors, MD3LightTheme } from 'react-native-paper';

const lightTheme = {
  ...MD3LightTheme,
  ...MD3LightTheme.colors,
  colors: {
    primary: 'rgb(0, 99, 154)',
    secondary: '#f4511e',
    whiteText: '#fff',

    outline: 'rgb(0, 95, 175)',
    background: 'rgb(255, 255, 255)',

    error: 'rgb(186, 26, 26)',
    onError: 'rgb(255, 255, 255)',
    errorContainer: 'rgb(255, 218, 214)',
    onErrorContainer: 'rgb(65, 0, 2)',
    tertiaryContainer: 'rgba(255, 216, 228, 1)',
    secondaryContainer: 'rgba(232, 222, 248, 1)',
    backdrop: '#fff',
    backdropCustom: 'rgba(44, 49, 55, 0.4)',
    disabled: MD3Colors.neutral50,
    successfull: 'rgb(50,205,50)',
    elevation: {
      level3: '#f4511e',
    },
    surface: 'rgba(255, 251, 254, 1)',
  },
  bordered: 6,
  fonts: {
    lobsterFontFamily: 'Lobster-Regular',
    robotoFontFamily: 'Roboto-Regular',
    robotoBold: 'Roboto-Bold',
    bodyLarge: {
      fontFamily: 'Roboto-Regular',
      fontSize: 16,
      fontWeight: '400',
      letterSpacing: 0.15,
      lineHeight: 24,
    },
    bodyMedium: {
      fontFamily: 'Roboto-Regular',
      fontSize: 14,
      fontWeight: '400',
      letterSpacing: 0.25,
      lineHeight: 20,
    },
    bodySmall: {
      fontFamily: 'Roboto-Regular',
      fontSize: 12,
      fontWeight: '400',
      letterSpacing: 0.4,
      lineHeight: 16,
    },
    default: {
      fontFamily: 'Roboto-Regular',
      fontWeight: '400',
      letterSpacing: 0,
    },
    displayLarge: {
      fontFamily: 'Roboto-Regular',
      fontSize: 57,
      fontWeight: '400',
      letterSpacing: 0,
      lineHeight: 64,
    },
    displayMedium: {
      fontFamily: 'Roboto-Regular',
      fontSize: 45,
      fontWeight: '400',
      letterSpacing: 0,
      lineHeight: 52,
    },
    displaySmall: {
      fontFamily: 'Roboto-Regular',
      fontSize: 36,
      fontWeight: '400',
      letterSpacing: 0,
      lineHeight: 44,
    },
    headlineLarge: {
      fontFamily: 'Roboto-Regular',
      fontSize: 32,
      fontWeight: '400',
      letterSpacing: 0,
      lineHeight: 40,
    },
    headlineMedium: {
      fontFamily: 'Roboto-Regular',
      fontSize: 28,
      fontWeight: '400',
      letterSpacing: 0,
      lineHeight: 36,
    },
    headlineSmall: {
      fontFamily: 'Roboto-Regular',
      fontSize: 24,
      fontWeight: '400',
      letterSpacing: 0,
      lineHeight: 32,
    },
    labelLarge: {
      fontFamily: 'Roboto-Medium',
      fontSize: 14,
      fontWeight: '500',
      letterSpacing: 0.1,
      lineHeight: 20,
    },
    labelMedium: {
      fontFamily: 'Roboto-Medium',
      fontSize: 12,
      fontWeight: '500',
      letterSpacing: 0.5,
      lineHeight: 16,
    },
    labelSmall: {
      fontFamily: 'Roboto-Medium',
      fontSize: 11,
      fontWeight: '500',
      letterSpacing: 0.5,
      lineHeight: 16,
    },
    titleLarge: {
      fontFamily: 'Roboto-Regular',
      fontSize: 22,
      fontWeight: '400',
      letterSpacing: 0,
      lineHeight: 28,
    },
    titleMedium: {
      fontFamily: 'Roboto-Medium',
      fontSize: 16,
      fontWeight: '500',
      letterSpacing: 0.15,
      lineHeight: 24,
    },
    titleSmall: {
      fontFamily: 'Roboto-Medium',
      fontSize: 14,
      fontWeight: '500',
      letterSpacing: 0.1,
      lineHeight: 20,
    },
  },
};

export default lightTheme;

// theme Object {
//   "animation": Object {
//     "scale": 1,
//   },
//   "backdrop": "rgba(50, 47, 55, 0.4)",
//   "background": "rgba(255, 251, 254, 1)",
//   "colors": Object {
//     "backdrop": "rgba(44, 49, 55, 0.4)",
//     "background": "rgb(255, 255, 255)",
//     "error": "rgb(186, 26, 26)",
//     "errorContainer": "rgb(255, 218, 214)",
//     "onError": "rgb(255, 255, 255)",
//     "onErrorContainer": "rgb(65, 0, 2)",
//     "outline": "rgb(0, 95, 175)",
//     "primary": "rgb(0, 99, 154)",
//     "secondary": "#f4511e",
//     "weather": "rgba(1, 142, 248, 0.72)",
//   },
//   "dark": false,
//   "elevation": Object {
//     "level0": "transparent",
//     "level1": "rgb(247, 243, 249)",
//     "level2": "rgb(243, 237, 246)",
//     "level3": "rgb(238, 232, 244)",
//     "level4": "rgb(236, 230, 243)",
//     "level5": "rgb(233, 227, 241)",
//   },
//   "error": "rgba(179, 38, 30, 1)",
//   "errorContainer": "rgba(249, 222, 220, 1)",
//   "fonts": Object {
//     "bodyLarge": Object {
//       "fontFamily": "System",
//       "fontSize": 16,
//       "fontWeight": "400",
//       "letterSpacing": 0.15,
//       "lineHeight": 24,
//     },
//     "bodyMedium": Object {
//       "fontFamily": "System",
//       "fontSize": 14,
//       "fontWeight": "400",
//       "letterSpacing": 0.25,
//       "lineHeight": 20,
//     },
//     "bodySmall": Object {
//       "fontFamily": "System",
//       "fontSize": 12,
//       "fontWeight": "400",
//       "letterSpacing": 0.4,
//       "lineHeight": 16,
//     },
//     "default": Object {
//       "fontFamily": "System",
//       "fontWeight": "400",
//       "letterSpacing": 0,
//     },
//     "displayLarge": Object {
//       "fontFamily": "System",
//       "fontSize": 57,
//       "fontWeight": "400",
//       "letterSpacing": 0,
//       "lineHeight": 64,
//     },
//     "displayMedium": Object {
//       "fontFamily": "System",
//       "fontSize": 45,
//       "fontWeight": "400",
//       "letterSpacing": 0,
//       "lineHeight": 52,
//     },
//     "displaySmall": Object {
//       "fontFamily": "System",
//       "fontSize": 36,
//       "fontWeight": "400",
//       "letterSpacing": 0,
//       "lineHeight": 44,
//     },
//     "headlineLarge": Object {
//       "fontFamily": "System",
//       "fontSize": 32,
//       "fontWeight": "400",
//       "letterSpacing": 0,
//       "lineHeight": 40,
//     },
//     "headlineMedium": Object {
//       "fontFamily": "System",
//       "fontSize": 28,
//       "fontWeight": "400",
//       "letterSpacing": 0,
//       "lineHeight": 36,
//     },
//     "headlineSmall": Object {
//       "fontFamily": "System",
//       "fontSize": 24,
//       "fontWeight": "400",
//       "letterSpacing": 0,
//       "lineHeight": 32,
//     },
//     "labelLarge": Object {
//       "fontFamily": "System",
//       "fontSize": 14,
//       "fontWeight": "500",
//       "letterSpacing": 0.1,
//       "lineHeight": 20,
//     },
//     "labelMedium": Object {
//       "fontFamily": "System",
//       "fontSize": 12,
//       "fontWeight": "500",
//       "letterSpacing": 0.5,
//       "lineHeight": 16,
//     },
//     "labelSmall": Object {
//       "fontFamily": "System",
//       "fontSize": 11,
//       "fontWeight": "500",
//       "letterSpacing": 0.5,
//       "lineHeight": 16,
//     },
//     "titleLarge": Object {
//       "fontFamily": "System",
//       "fontSize": 22,
//       "fontWeight": "400",
//       "letterSpacing": 0,
//       "lineHeight": 28,
//     },
//     "titleMedium": Object {
//       "fontFamily": "System",
//       "fontSize": 16,
//       "fontWeight": "500",
//       "letterSpacing": 0.15,
//       "lineHeight": 24,
//     },
//     "titleSmall": Object {
//       "fontFamily": "System",
//       "fontSize": 14,
//       "fontWeight": "500",
//       "letterSpacing": 0.1,
//       "lineHeight": 20,
//     },
//   },
//   "inverseOnSurface": "rgba(244, 239, 244, 1)",
//   "inversePrimary": "rgba(208, 188, 255, 1)",
//   "inverseSurface": "rgba(49, 48, 51, 1)",
//   "isV3": true,
//   "onBackground": "rgba(28, 27, 31, 1)",
//   "onError": "rgba(255, 255, 255, 1)",
//   "onErrorContainer": "rgba(65, 14, 11, 1)",
//   "onPrimary": "rgba(255, 255, 255, 1)",
//   "onPrimaryContainer": "rgba(33, 0, 93, 1)",
//   "onSecondary": "rgba(255, 255, 255, 1)",
//   "onSecondaryContainer": "rgba(29, 25, 43, 1)",
//   "onSurface": "rgba(28, 27, 31, 1)",
//   "onSurfaceDisabled": "rgba(28, 27, 31, 0.38)",
//   "onSurfaceVariant": "rgba(73, 69, 79, 1)",
//   "onTertiary": "rgba(255, 255, 255, 1)",
//   "onTertiaryContainer": "rgba(49, 17, 29, 1)",
//   "outline": "rgba(121, 116, 126, 1)",
//   "outlineVariant": "rgba(202, 196, 208, 1)",
//   "primary": "rgba(103, 80, 164, 1)",
//   "primaryContainer": "rgba(234, 221, 255, 1)",
//   "roundness": 4,
//   "scrim": "rgba(0, 0, 0, 1)",
//   "secondary": "rgba(98, 91, 113, 1)",
//   "secondaryContainer": "rgba(232, 222, 248, 1)",
//   "shadow": "rgba(0, 0, 0, 1)",
//   "surface": "rgba(255, 251, 254, 1)",
//   "surfaceDisabled": "rgba(28, 27, 31, 0.12)",
//   "surfaceVariant": "rgba(231, 224, 236, 1)",
//   "tertiary": "rgba(125, 82, 96, 1)",
//   "tertiaryContainer": "rgba(255, 216, 228, 1)",
//   "version": 3,
// }
